spring:
  application:
    name: task
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: task
      repositories:
        type: auto

# Validation
  messages:
    basename: validation-messages

# Client
via:
  cep:
    url: https://viacep.com.br/ws
