spring:
  application:
    name: task
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: task
      repositories:
        type: auto
  cloud:
    config:
      enabled: false
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: br.com.jnsdev.task.model

  # Validation
  messages:
    basename: validation-messages

kafka:
  task:
    notification-output: task-notification-v1

# Client
via:
  cep:
    url: https://viacep.com.br/ws
